spring:
  datasource:
    url: jdbc:h2:mem:clients # Em produção normalmente seria utilizado um banco real, como Postgres.
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false
