spring:
  application:
    name: Clients API
  datasource:
    url: jdbc:h2:mem:clients
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

security:
  jwt:
    signing-key: V3WNdstGAyT35CUnZNDMLjcM5dtk1dFUCesi9y8sKpfNP6qmw290Fsi/Wj+G+qrPepQhHxPtv2a3MSQk22y9Qw==
    expiration: 3600000
